config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50}
  # Regex matches valid emails:
  # (any word, +, -, or .)@(at least a letter, -, #, or .).(at least a letter)
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      # if checkbox is selected, remember user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email / password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
    current_user.update_attribute(:bio, params[:user][:bio])
    redirect_to current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully edited!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.update_attribute(:bio, "#{@user.name} hasn't made a bio yet!")
      log_in @user
      remember @user
      flash[:success] = "Welcome to #{ Rails.application.config.TITLE }!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Sign up or log in before continuing"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def get_first_name
    name.split[0]
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return unique title for each page
  def full_title (page_title = '')
    base_title = Rails.application.config.TITLE
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns currently logged in user, or nil if none
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user? (user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#"><%= Rails.application.config.TITLE %></a>
    by <%= link_to "Dylan Rainwater", 'http://www.github.com/dylanrainwater' %>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
				<%= link_to (Rails.application.config.TITLE + "."), root_path, id: "logo" %>
				<nav>
						<ul class="nav navbar-nav navbar-right">
								<li><%= link_to "Home", root_path %></li>
								<% if logged_in? %>
									<li><%= link_to "Users", users_path %></li>
									<li class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">
											Hey, <%= current_user.name.split[0] %> <b class="caret"></b>
										</a>
										<ul class="dropdown-menu">
												<li><%= link_to "Profile", current_user %></li>
												<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
												<li class="divider"></li>
												<li>
														<%= link_to "Log out", logout_path, method: :delete %>
												</li>
										</ul>
									</li>
									<% else %>
										<li><%= link_to "Log in", login_path %></li>
									<% end %>
						</ul>
				</nav>
		</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title))%></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About <%= Rails.application.config.TITLE %></h1>

<p>
    (More to come...)
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<p>
    Hey! I'm Dylan. <br>
    You can contact me on <a href="https://www.github.com/dylanrainwater">Github</a>
    or through email at <a href="mailto:dylan@volhacks.org">dylan@volhacks.org</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to <%= Rails.application.config.TITLE %></h1>

  <h2>
    /'barkər/ - your new favorite social media platform 
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<h1>Editing Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :bio %>
      <%= f.text_field :bio, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% plural_title = Rails.application.config.TITLE +  's' %>
<% provide(:title, plural_title) %>
<h1>Fellow <%= plural_title %> </h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each_with_index do |user, index| %>
    <li class=<%= (index % 2 == 0) ? "even" : "odd"%>>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
      <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete, data: { confirm: "Delete?" } %>
        <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Join #{ Rails.application.config.TITLE }", class: "btn btn-primary" %>
    <% end %>

    <p> <em>Pssst</em>, already a brkr? <%= link_to 'Click here!', login_path %> </p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
          <%= gravatar_for @user %>
          <%= @user.name %><br>
          <small>Image retrieved from <a href="https://www.gravatar.com">gravatar</a>
          </small> <br>

      </h1>
    </section>
  </aside>

  <aside class="col-md-<%= current_user == @user ? 7 : 8 %> bio">

      <blockquote class="blockquote">
        <p><%= @user.bio %></p>
        <footer><%= @user.name %> </footer>
      </blockquote>

  </aside>
<% if current_user == @user %>
    <aside class="col-md-1">
      <section>
        <h1>

            <%= link_to "Edit Profile", edit_user_path(current_user),
                                    class: "btn btn-primary btn-sm" %>

        </h1>
      </section>
    </aside>
  </div>
<% end %>